[package]
name = "HierarchicalCache"
version = "0.1.0"
authors = ["devillove084"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = "0.7.0"
crossbeam-epoch = "0.8.2"
num_cpus = "1.12.0"
rayon = {version = "1.3", optional = true}
serde = {version = "1.0.105", optional = true}
indexmap = "1.6"
log = "0.4"
probabilistic-collections = "0.7"
tokio = { version = "1.0.0", features = ["full"] }
tokio-util = { version = "0.6.0", features = ["codec"] }
shlex = "0.1.1"
promptly = "0.1.5"
rand = "0.7.2"
bytes = { version = "1.0.0", features = ["serde"] }
sloggers = "0.3.4"
lazy_static = "1.4.0"
slog = "2.5.2"
serde_derive = "1.0.123"
bincode = "1.2.0"
structopt = "0.3.5"
directories = "2.0.2"
parking_lot = { version = "0.10.0", features = ["serde"] }
rmp-serde = "0.14.0"
spin = "0.5.2"
growable-bloom-filter = "0.2.3"
seahash = "3.0.6"
futures = "0.3.1"
futures-util = "0.3.1"
serde_bytes = "0.11.3"
dashmap = { version = "4.0.2", features = ["serde"] }
memchr = "2.3.0"
smallvec = "1.4.1"
x7 = { git = "https://github.com/dpbriggs/x7.git", version = "*" }
num-traits = "0.2.14"

[dev-dependencies]
criterion = "0.3"
serde_json = "1.0.50"
